# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2

resources:
  ### Install: NotePad++
  ### -------------------------------------
  - resource: Microsoft.WinGet.DSC/WinGetPackage
    id: Notepad++
    directives:
      description: Install Notepad++
      allowPrerelease: true
    settings:
      id: Notepad++.Notepad++
      source: winget
      ensure: Present

  ### Install: 7Zip
  ### -------------------------------------
  - resource: Microsoft.WinGet.DSC/WinGetPackage
    id: 7Zip
    directives:
      description: Install 7Zip
      allowPrerelease: true
      minimumVersion: "23.01"
    settings:
      id: "7zip.7zip"
      source: winget
      ensure: Present

  ### Install: NVAccess.NVDA
  ### -------------------------------------
  - resource: Microsoft.WinGet.DSC/WinGetPackage
    id: NVDA
    directives:
      description: Install NVAccess.NVDA
      allowPrerelease: true
    settings:
      id: NVAccess.NVDA
      source: winget
      ensure: Present

  ### Install: Freedom Scientific JAWS 2023
  ### -------------------------------------
  - resource: Microsoft.WinGet.DSC/WinGetPackage
    id: JAWS
    directives:
      description: Freedom Scientific JAWS 2023
      allowPrerelease: true
    settings:
      id: FreedomScientific.JAWS.2023
      source: winget
      ensure: Present

configurationVersion: 0.2.0
